### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by alin2462** [bhb27/smarttv-twitch#1]
Hello,

Thanks for the new updates. I just installed the application on my Samsung TV(40K6372 firmware 1201). I can see the live channels and when I select one to watch - the loading takes a lot of time to finish, and when it finishes the screen remains black. I also tried switching the quality to lower ones but no success. Is there any fix for this?

**Comment by bhb27** [comment]
I only test this on a 4k model I don't have a FHD tv like that...
on the past this was done:
https://github.com/bhb27/smarttv-twitch/commit/6aadf823e3e2dc13692b9f20b10d99ce5fba6e40

can you try that and see what happnes?

maybe is that I'm not shore...

**Comment by bhb27** [comment]
I made a update if the problem was the resolution
https://github.com/bhb27/smarttv-twitch/commit/a1e67a85b6affb05268866c9fdf0fedd3dfda13f

just update the source and test

**Comment by alin2462** [comment]
It works perfectly! Thank you so much. I can finally watch twitch.

I'll make sure to keep up with the new updates :D
