### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by dantearaujo1** [bhb27/smarttv-twitch#10]
An internal error occurred during: "Launching Twitch".
java.lang.NullPointerException

**Comment by bhb27** [comment]
Have you read the "In doubt or a featuring request open a issue"? at https://github.com/bhb27/smarttv-twitch#in-doubt-or-a-featuring-request-open-a-issue

**Comment by dantearaujo1** [comment]
No, i didn't. Now i solved my issue! Thank you !

**Comment by bhb27** [comment]
OK
