### ISSUE TITLE
2015 TV model running Tizen 2.3, can't play bug [Testers needed]

### ISSUE THREAD

**Issue by bhb27** [bhb27/smarttv-twitch#12]
Tizen OS version 2.3 that runs on some of the 2015 TV models, has a know bug this app will install, work but will not play **Live** content and some **Videos (Past Broadcast and Highlights)**.

To check if yours TV has this bug you just install the app and try to play **Live** and **Videos (Past Broadcast and Highlights)** streams if they fail and yours TV is a 2015 model and you wanna to help, post here yours TV models and test made.

The test are needed as Samsung will make fixes when requested but on the same time they do request very specific test with logs and information to be share back to them, as I don't have the TV I can't test or share wherever they will ask.

This problem doesn't happens if the TV received Tizen 2.4 update even if is a 2015 model.

Tizen version, TV model and Firmware can be see on the about section of this app (Use Key A or RED)

**Comment by xar4567** [comment]
More than happy to help if you can let me know what you need.  I've got a 2015 model TV, running Tizen 2.3.  Model number is UJU6400 running firmware version T-HKMUABC-1530.0

**Comment by bhb27** [comment]
The last report is that Samsung has fix they api player, the current release version doesn't use that api player as it had others bug on the past, but they are all resolved.

So is needed to test this branch:
https://github.com/bhb27/smarttv-twitch/archive/avply_test.zip

That branch has support for Samsung player, but it is a old branch and doesn't have all latest updates of the main **master** branch and it have some bugs...

But it can be use until I have finished porting the Samsung player to the master branch.

If @xar4567, @Xanvial or anyone else have time to test that branch (https://github.com/bhb27/smarttv-twitch/archive/avply_test.zip) and let me know the result I'll appreciate...

The process of installation is the same as the release, download that link extract and fallow all the others instructions from (https://github.com/bhb27/smarttv-twitch#installation-guide-tizen-studio-tested-on-linux-ubuntu-1804-and-windows-10-64-bits).

If all OK I start working on the update of the main branch and probably have something released on the weekend.

Be aware as that branch is old ans has bugs the app may freeze, if it does hold the **return** key down until the app force close.

In doubt let me know.

**Comment by bhb27** [comment]
If the released did not worked, I would not share it like that all is needed is in there.

The only diference from run the app from the repo and from the released, is that the repo will contains all the .js code in the app.wgt file sendo to the TV, and the release will pull that from the server. That is how I test and update things without user interaction as the file be puled is not the same be tested, but is all there on the same git.io server.

And there is other then .js files be puled from the server, and both way to install pull all the others files from there the only not be puled is the .js one, so if the problem is to pull a file the problem must be on all files and not just the .js one and installing from the repo must not work properly also, as all the css class come from the server you would not be able see the proper way, so if you can see a top bar saying **Live User etc...** and can change what video and screens, the "pulling" things from the server is fine.

So have you try to use the release after fw update, and if there is a problem have you log it?
It may be just a bad install or may be some other TV problem related to that model.

**Comment by Xanvial** [comment]
Btw, I add some log on avply_test code, it stuck on line Play.avplay.prepare(); line 442 in Play.js, in case it helps

**Comment by bhb27** [comment]
Yes it was the FW regarding the release.

@Xanvial I need you to try somethings so I can have all the info to share with Samsung, all the test are in the **avply_test** branch.

Can you change this line
https://github.com/bhb27/smarttv-twitch/blob/avply_test/index.html#L374

	<script src="$WEBAPIS/webapis/webapis.min.js" defer></script>

with:

	<script src="$WEBAPIS/webapis/webapis.js" defer></script>

Just remove the **min.**, just to make shore that is not the problem because those files can be diferente.

If that doesn't help, I need also you to test **Past broadcast** and see if some play or not, on the pass some played usually those whit less then 4 hours of duration, so try those some whit a few hours some with more 2+ 4+ 6+ 9+.

**Comment by bhb27** [comment]
@Xanvial 

you can comment out this two lines (add a **//** on the line start)
https://github.com/bhb27/smarttv-twitch/blob/avply_test/app/specific/SmartHub.js#L54-L55

to prevent this:

	TypeError: 'undefined' is not an object (evaluating 'webapis.preview.setPreviewData') SmartHub.js:54

that is a Tizen 2.4 featuring that I need prevent from run base on OS version.

I doubt that it is affecting the players result but will not cause those unnecessary logs.

**Comment by bhb27** [comment]
Clips are .mp4 files, you can open those just fine, in the clip section of a channel, or in the clip section of the release.

**Have you try different duration? as I post before?
I really need the test on different duration above 4+ hours.**

Because the problem on past broacast are only on very long saved stream, the live problem is different.

If you open those .m3u8 files you will see that live and past broadcast are different you can use the link do download those and open using a txt editor.

Samsung knows that the problem is on those m3u8 settings that you can see when you open those.

**Comment by bhb27** [comment]
Those link erros are just bad internet connection, you can test those on a browser and see that they open just fine.

In the case they don't for the app do to a internet momentary fail, the app will load a fail safe **img** and keep loading others files just fine not a big deal.

when the app loads the fail safe img you see something like this:

![fail_img](https://bhb27.github.io/smarttv-twitch/images/404_video.png)
![fail_img2](https://bhb27.github.io/smarttv-twitch/images/404_logo.png)

**Comment by bhb27** [comment]
Samsung only test the link from Twitch on they player

So I have mod they player to load a Live and a VOD (video on demand past broadcast)

Before I tell they that one problem is OK VOD, but Live is not I need the test from they player

The bellow file is they player:
[TestPlayer.zip](https://github.com/bhb27/smarttv-twitch/files/2006053/TestPlayer.zip)

You install just like a normal app, after it loads you use key up/down to navigate and press the play key to start playing.

I need you to install the app and press play after the Live link has loaded and tell me the result...
 when the app finish load you see this:

![frame001_w1920h1080](https://user-images.githubusercontent.com/13755892/40073574-96fbb44c-584d-11e8-9916-a35d4a5c8e07.png)

**Comment by bhb27** [comment]
@Xanvial I post a lot of things up there in doubt let me know. no rush... :+1:

**Comment by Xanvial** [comment]
And this is when playing VOD, it show some image, I think it should be a video but the buffering time take a while until 100. It has some animation when reaching 100 and then buffering again
```
[PlayerAvplayDRM]:  Starting playback main.js:13
[PlayerAvplayDRM]:  videoPlayer open: http://vod093-ttvnw.akamaized.net/c59963b1beb162fbe990_ninja_28643839600_858910139/chunked/index-muted-4CDW0MDTA8.m3u8 main.js:13
[PlayerAvplayDRM]:  setDrm Playready param: {"DeleteLicenseAfterUse":true} main.js:13
[PlayerAvplayDRM]:  Buffering start. main.js:13
[PlayerAvplayDRM]:  event type: PLAYER_MSG_BITRATE_CHANGE, data:  main.js:13
[PlayerAvplayDRM]:  event type: PLAYER_SPARSE_TRACK_DETECT, data: AAAAAilUUkNLAAAAAwAAAzAAVERFTgAAABUAAAMyMDE4LTA1LTEwVDE0OjIwOjUyAFREVEcAAAAVAAADMjAxOC0wNS0xMFQxNDoyMDo1NgBUT0ZOAAAAGgAAA2luZGV4LTAwMDAwMDAwMDAtQkZqMy50cwBUU1NFAAAAFQAAA2xpYmF2dHdpdGNoOiA2N2Y0MGUAVFhYWAAAAREAAANzZWdtZW50bWV0YWRhdGEAeyJicm9hZGNfcyI6MSwiY21kIjoibGRfbGF0X2RhdGEiLCJpbmdlc3RfciI6MiwiaW5nZXN0X3MiOjMsInN0cmVhbV9vZmZzZXQiOjAsInRyYW5zY19yIjoxNTI1OTYyMDUyNDg0LCJ0cmFuc2NfcyI6MTUyNTk2MjA1NjY3Nn0=|68348000000 main.js:13
6
[PlayerAvplayDRM]:  Current playtime: 168 main.js:13
[PlayerAvplayDRM]:  Buffering progress data : 4 main.js:13
3
[PlayerAvplayDRM]:  Current playtime: 168 main.js:13
[PlayerAvplayDRM]:  Buffering progress data : 6 main.js:13
[PlayerAvplayDRM]:  Buffering progress data : 7 main.js:13
2
[PlayerAvplayDRM]:  Current playtime: 168 main.js:13
[PlayerAvplayDRM]:  Buffering progress data : 9
```

Using Playready GetChallange, there's some image shown a few milliseconds and then disapper, here's the log
```
[PlayerAvplayDRM]:  Live link: http://video-weaver.sin01.hls.ttvnw.net/v1/playlist/CoYDbyO-FE4gNBdCiR0-uuvg0wlTTOYBtbryut3B6lV-Mz-nmO2-nZhKX3Gc7UP8OMv1Q93GjQjKiBGhoXM36d3e31ivF_NHw_LpOW8_ORNgSFIBKWAYMKmgO3gZCDnDBUTcrac0kfR7g_YWUMhbOkvilSNVh-oN59a6j0J4SNX--CJmlW8_cO0OBayRdKLxNAWn3SiIw67iTNQDMbLM2kAWyUxQ83RgKXp7bKdZDeOo3wqqeaSy5qzgodqGVeyQBPTCcPUnrB3kgXvvzentbA90L8RV_f7SV8B9wpBk2VuoJRsqQ3H2AlOaFUpjCOPvIuyaJ8Kz4lwbWFuXOzCtH7ojNjdHJvPFpozC-vcyUll2rDLyY4lmRNmptLfrMtFhjSJ3Jhda8mBMx9MJvkL94Vpxx3sE3xD2xBqY7A5CcySR-90zM9n-36cf_9RqUabaLvoSngjaSTDfrcbF3OwG3KsaRvb22Vs_PHDj5tRso-5dsSd87P9bZ8OuOoLoa40eOtxd2wVgdJypEhCo4Jsf6KfbocSPbLOVzH_wGgyNyL7sCeyhZlOq3No.m3u8 main.js:13
[PlayerAvplayDRM]:  VOD link: http://vod093-ttvnw.akamaized.net/c59963b1beb162fbe990_ninja_28643839600_858910139/chunked/index-muted-4CDW0MDTA8.m3u8 main.js:13
[PlayerAvplayDRM]:  The display width is 1280 main.js:13
[PlayerAvplayDRM]:  Starting playback main.js:13
[PlayerAvplayDRM]:  videoPlayer open: http://playready.directtaps.net/smoothstreaming/SSWSS720H264PR/SuperSpeedway_720.ism/Manifest main.js:13
[PlayerAvplayDRM]:  setDrm Playready GetChallenge param: {"DeleteLicenseAfterUse":true,"GetChallenge":true} main.js:13
[PlayerAvplayDRM]:  Buffering start. main.js:13
[PlayerAvplayDRM]:  Buffering complete. main.js:13
[PlayerAvplayDRM]:  event type: PLAYER_MSG_BITRATE_CHANGE, data:  main.js:13
[PlayerAvplayDRM]:  DRM callback: PLAYREADY, data: [object Object] main.js:13
[PlayerAvplayDRM]:  event type: PLAYER_MSG_BITRATE_CHANGE, data:  main.js:13
[PlayerAvplayDRM]:  event type error : UNKNOWN_ERROR_EVENT_FROM_PLAYER main.js:13
```

The Widevine one plat without a problem, almost no buffering
```
[PlayerAvplayDRM]:  Live link: http://video-weaver.sin01.hls.ttvnw.net/v1/playlist/CoYDoLL8vkWbHNpheLRxmlDXurVvpDFCOG5Ff6kFP12oIKOhLYoy0EtNx8iw2ALY4o36cMRhTwcxcYmfo_qu51BKKwz9BQp0cSUURc7yoAUKvy7dKrfW7q9p5ge5qTYw8WwdzFFhCwCLUIZyRnDlrgEEFYGiaBkES8G418p0qUwXo_P65SFiPbLs0y9to6S620QO_m8lxSNVi9WX16Sw05h1HkfX2NgCZI3G_yl9sXQcM04pL0hDR491eMBXrHsLWcWx9JnxtFqwCj9U3IjiYrL6tjL5xmsRXwcaafUC0c4BP6XjP4Qh8XlaDpmH4hMSfQW9X_aGClzAzFndGCituE6nOjHGWtpoIID2PUaXE16JD6HMEVX2TpmZnxyObkA2yzOymZJ1sgmdcVmW2q8DWi_Cp6SUQQgfStm010VuH_GmZ5aUeh3SctV6omT6z7SeBs2AJCXnEsqRSNUtMEaK1MxmXxqLR6wxDn6be0J0IuIucU4QGlRqZOo4JfGD1utv_PSTQO6wxa32EhDIRU1bz25ynwVRcauNLvj1GgwRhBP7j2O4Uwifxz0.m3u8 main.js:13
[PlayerAvplayDRM]:  VOD link: http://vod093-ttvnw.akamaized.net/c59963b1beb162fbe990_ninja_28643839600_858910139/chunked/index-muted-4CDW0MDTA8.m3u8 main.js:13
[PlayerAvplayDRM]:  The display width is 1280 main.js:13
[PlayerAvplayDRM]:  Starting playback main.js:13
[PlayerAvplayDRM]:  videoPlayer open: http://commondatastorage.googleapis.com/wvmedia/starz_main_720p_6br_tp.wvm main.js:13
[drminfo.js]  message data SSTVF6339868845 /opt/down/pepper/webapis/webapis.js:439
[PlayerAvplayDRM]:  setStreamingProperty Widevine param: DEVICE_ID=SSTVF6339868845|DEVICE_TYPE_ID=60|STREAM_ID=|IP_ADDR=|DRM_URL=https://license.uat.widevine.com/getlicense/widevine|PORTAL=OEM|I_SEEK=|CUR_TIME=|USER_DATA= main.js:13
[PlayerAvplayDRM]:  Buffering start. main.js:13
[PlayerAvplayDRM]:  Buffering complete. main.js:13
[PlayerAvplayDRM]:  Current playtime: 1134 main.js:13
[PlayerAvplayDRM]:  Current playtime: 2135 main.js:13
[PlayerAvplayDRM]:  Current playtime: 3136 main.js:13
[PlayerAvplayDRM]:  Current playtime: 4137 main.js:13
[PlayerAvplayDRM]:  Current playtime: 5138 main.js:13
[PlayerAvplayDRM]:  Current playtime: 6139 main.js:13
[PlayerAvplayDRM]:  Current playtime: 7140 main.js:13
[PlayerAvplayDRM]:  Current playtime: 8141 main.js:13
[PlayerAvplayDRM]:  Current playtime: 9142 main.js:13
[PlayerAvplayDRM]:  Current playtime: 10143 main.js:13
[PlayerAvplayDRM]:  Current playtime: 11144 main.js:13
```

Btw, what do you mean with openin the m3u8 file? Should I do that? Playing the link inside the file?

**Comment by bhb27** [comment]
can you share to me the log of this crashe

**Comment by bhb27** [comment]
Can you share to me the log of this crashes please the one were you wrote

> About your request. I try to play multiple past broadcast. Turn out when I try to play ~6 hour and ~10 hour the application is buffering for a while and then crashed (return to main tv screen). It works correctly on ~2 hour clip

**Comment by bhb27** [comment]
The Playready and Widevine options are't twitch links they come Hardcoded on the Samsung test app.

We only need to test the Live and VOD option.

**Comment by bhb27** [comment]
When I have

	<tizen:privilege name="http://developer.samsung.com/privilege/drminfo"/>

On config.xml the Tizen studio doesn't let me install the app I get this.

![screenshot from 2018-05-16 16-45-30](https://user-images.githubusercontent.com/13755892/40141225-ad1e0f84-592b-11e8-9c23-5a811c444ae3.png)

Whit is very odd, removing is not a problem at least here not for install, and not for a playback also because the twitch links are not using DRM.

So is not a thing to worry.

**Comment by bhb27** [comment]
@Xanvial 
After you share to me those crashes logs I have all the info needed to share with samsung to start resolve this bug for now.

I appreciate the help thanks.

:+1:

**Comment by Xanvial** [comment]
I'm not sure about the drminfo line, because even when it's error I can still run the application.
How can I get the crash log? IIRC it didn't shown on console log

**Comment by bhb27** [comment]
I just need to see what shows on the console log, not the crash it self.
As on the log the link that cause the crash will be there so I will share the link with Samsung so they can cause the crash there and them there evaluated what is happening.

Because on the console we have is limited, but having the link we can try to solve.

**Comment by bhb27** [comment]
That is all I need, some links that crash things, so they can fixe it...

**avplay** is crashing trying to setup the m3u8 file some how, the odd things is that some videos works and some don't and the only difference the the duration, with make me to believed that this bug can be random, as samsung guaranties that they fix it in fw 1530 but they did't fully.

If you wanna to share more of those that crashes things you can.
I will share them all with Samsung and after they say is working we need to test again and again until is really always working.

**Comment by Xanvial** [comment]
I'll test with other broadcast link later. Anything else that I can do?

**Comment by bhb27** [comment]
OK, nothing else for now to do...

I finished porting the avplay to the app here
https://github.com/bhb27/smarttv-twitch/commits/avply_master

I will test for a day then merge it to the release.
If you wanna to use that branch for test you can.

I manage to fix a app bug were the player was closing when trying to play a video and a internet error occurs, this error did not crashed the app but makes believed that a OK link is bad.

So on future test on the app when Samsung update things related to avplay will be much easier to test as there is only bugs from the OS/API it self.

**If anyone has anything to add on this please do.**

:+1:

**Comment by bhb27** [comment]
I migrate all to **master** branch now there is only need to test that one.

**Comment by saarsc** [comment]
I have J5500 

The latest version doesn't load streams for me
If you need any help hit me up

**Comment by bhb27** [comment]
Samsung answer...

![screenshot from 2018-06-11 13-57-07](https://user-images.githubusercontent.com/13755892/41245942-e287ef7e-6d7f-11e8-8b38-1e545b673d1b.png)

**Don't you guys can play Live stream from youtube?**

I really did not like this answer it seems that Samsung doesn't wanna to fix the problem, 

From the reports I received, live stream played just fine last years and from noting they stop, I assume is a change on the OS or how Twitch shares the links, in both cases seems something possible to fix on the OS side.

**Comment by saarsc** [comment]
I can confirm that the OG version of the app did indeed work without any problem for a long time and then someday it just stopped working
