### ISSUE TITLE
Plans to add chat?

### ISSUE THREAD

**Issue by xt449** [bhb27/smarttv-twitch#15]
Are you planning on adding this soon?

I'd like to help work on this; however, I do not have a good build/deploy/test system.
Is there any way i can streamline the process of uploading the new changes to the tv to test?

**Comment by bhb27** [comment]
You can check controls pressing the "C or yellow key", to enable chat using the info or guide key, only available for live stream some day to other (clips and videos) .
I don't plane to add the option to write on chat.

If you wanna to test, the best way is, to install the source and not the release zip, as you make change you install the app again using the "ladybug" icon on the top of tizen sdk, the "ladybug" enable login so you can see if the changes work or not and maybe see way.

as long as you change the app id you can have more then on version installed, just change the "qY6HyNzLIR" in https://github.com/bhb27/smarttv-twitch/blob/master/config.xml#L4 for a new random string with 10 characters, this way you can keep a stable and a test version all the time.

**Comment by bhb27** [comment]
If you need open this again.
