### ISSUE TITLE
Logging in to Twitch

### ISSUE THREAD

**Issue by ubergeek77** [bhb27/smarttv-twitch#7]
How do we log in to Twitch with this app? The authentication page isn't very clear. All it says is:

Enter the bellow characters on the app screen (There is only lower case letters)

Followed by my auth token. I have my auth token, but I have no idea how to use it. I should note that I have the most recent master installed to my TV (not the 4.0.0 release) Can you help me?

Thanks!

(As a side note, you'll be happy to know that this is working perfectly on my MU9000 65" TV. MUCH better than the Twitch app available on the App Store!)

**Comment by ubergeek77** [comment]
Actually, I just figured it out!

For everyone's benefit:

Visit the User tab first, type the user name you want to log in with, THEN provide your key. And it works!

**Comment by bhb27** [comment]
The featuring is new I did not had time to revise it. Is better now.
